
albertsons_mapping = {
    "Dairy, Eggs & Cheese": 3,
    "Deli Cheese": 3,
    "Fresh Fruits": 1,
    "Fresh Vegetables & Herbs": 2,
    "Packaged Salads": 2,
    "Tofu & Meat Alternatives": 2,
    "Packaged Vegetables": 2,
    "Pet Care": 17,
    "Frozen Foods": 18,
    "Prepared & Frozen Meat": 18,
    "Beverages": 6,
    "Iced & Nitro Coffee": 6,
    "Personal Care & Health": 13,
    "Deli Meat": 4,
    "Salami & Lunch Meats": 4,
    "Deli": 0,
    "Packaged Dips & Mix": 0,
    "Sausage,Hot Dogs & Bacon": 4,
    "Canned Goods & Soups": 7,
    "Chicken & Turkey": 4,
    "Beef": 4,
    "Pork": 4,
    "Lamb": 4,
    "Fish & Shellfish": 5,
    "Packaged Fresh Fruit": 1,
    "Nuts & Dried Fruits": 9,
    "Paper, Cleaning & Home": 14,
    "Condiments, Spice & Bake": 9,
    "Sauces, Marinades & Mixes": 8,
    "Honey, Syrup & Nectar": 8,
    "Jam,Spreads & Condiments": 8,
    "Salad Dressing & Topping": 8,
    "Vinegar & Oil": 8,
    "Pickles, Relish & Olives": 7,
    "International Cuisine": 20,
    "Cookies, Snacks & Candy": 10,
    "Breakfast & Cereal": 11,
    "Grains, Pasta & Sides": 9,
    "Wine, Beer & Spirits": 15,
    "Cleaners & Supplies": 16,
    "Dish Detergents": 16,
    "Laundry": 16,
    "Air Fresheners & Candles": 16,
    "Coffee": 9,
    "Tea Bags": 9,
    "Flavored Syrups": 9,
    "Baby Care": 19,
    "Supplements": 0,
    "Bread & Bakery": 12,
    "Flowers": 0,
}